[package]
name = "nes"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.8.0"
fastrand = "2.3.0"
log = "0.4.25"
sdl2 = { version = "0.37.0", features = ["bundled"] }
simple_logger = "5.0.0"
